module.exports = [
    {mountain_id:"513", name: 'Arapahoe Basin'},
    {mountain_id:"1032", name: 'Aspen Highlands'},
    {mountain_id:"1031", name: 'Aspen Mountain'},
    {mountain_id:"497", name: 'Beaver Creek Resort'}, 
    {mountain_id:"2669", name: 'Berthoud Pass'},
    {mountain_id:"510", name: 'Breckenridge Ski Resort'},
    {mountain_id:"504", name: 'Buttermilk Mountain'}, 
    {mountain_id:"3296", name: 'Chapman Hill Ski Area'}, 
    {mountain_id:"13153", name: 'Cimarron Mountain Club'}, 
    {mountain_id:"509", name: 'Copper Mountain Resort'}, 
    {mountain_id:"3297", name: 'Cranor Hill Ski Area'}, 
    {mountain_id:"514", name: 'Crested Butte Mountain Resort'}, 
    {mountain_id:"13787", name: "Devil's Thumb"}, 
    {mountain_id:"1034", name: 'Echo Mountain'}, 
    {mountain_id:"508", name: 'Eldora Mountain Resort'}, 
    {mountain_id:"4904", name: 'Frisco Adventure Park'}, 
    {mountain_id:"1035", name: 'Hesperus Ski Area'}, 
    {mountain_id:"498", name: 'Howelsen Hill Ski Area'}, 
    {mountain_id:"13028", name: 'Irwin Lodge Snowcat'}, 
    {mountain_id:"499", name: 'Kendall Mountain'}, 
    {mountain_id:"519", name: 'Keystone Resort'}, 
    {mountain_id:"3298", name: 'Lake City Ski Hill'}, 
    {mountain_id:"3299", name: "Lee's Ski Hill"}, 
    {mountain_id:"515", name: 'Loveland'}, 
    {mountain_id:"520", name: 'Powderhorn Resort'}, 
    {mountain_id:"518", name: 'Purgatory (Durango Mountain Resort)'}, 
    {mountain_id:"5179", name: 'Silver Hills'}, 
    {mountain_id:"2280", name: 'Silverton Mountain'}, 
    {mountain_id:"512", name: 'Ski Cooper'}, 
    {mountain_id:"516", name: 'Ski Granby Ranch'}, 
    {mountain_id:"1033", name: 'Snowmass'}, 
    {mountain_id:"500", name: 'Steamboat Ski Resort'}, 
    {mountain_id:"506", name: 'Sunlight Mountain Resort'}, 
    {mountain_id:"517", name: 'Telluride'}, 
    {mountain_id:"507", name: 'Vail'}, 
    {mountain_id:"503", name: 'Winter Park Resort'}, 
    {mountain_id:"505", name: 'Wolf Creek Ski Area'} 
] 

